### ISSUE TITLE
Clean Architecture: A Craftsman's Guide to Software Structure and Design

### ISSUE THREAD

**Issue by sergioalvz** [privacycloud/book-club#21]
# Clean Architecture: A Craftsman's Guide to Software Structure and Design

I've not been a big fan of _Uncle Bob_ recently but this book might be helpful for us to read...

- What is it?
  - [x] A book 📚
  - [ ] An article 📄
  - [ ] Other
- Link: https://www.amazon.es/Clean-Architecture-Craftsmans-Software-Structure/dp/0134494164

**Comment by sergioalvz** [comment]
First meeting on Feb 26th 2019 at 4pm.

**Comment by sergioalvz** [comment]
Mar 12th 2019: chapter 7.

**Comment by sergioalvz** [comment]
March 19th: chapter 8 (Rober)

**Comment by sergioalvz** [comment]
March 26th: chapter 9 (Rober)

**Comment by sergioalvz** [comment]
Apr 2nd: chapter 10 (Sergio)

**Comment by sergioalvz** [comment]
April 9th: chapter 11 (Santi)

**Comment by sergioalvz** [comment]
«A framework-independent, decoupled frontend architecture for large-scale projects»: https://youtu.be/yDlp2o2Eh7Q

—-

April 23rd: chapter 13 (Sergio)

**Comment by SantiMA10** [comment]
> «A framework-independent, decoupled frontend architecture for large-scale projects»: https://youtu.be/yDlp2o2Eh7Q
> 

Slides: https://docs.google.com/presentation/d/1ZJGXMuMf_YOSFCDF78AVA9ylk7CH_uLNc3HqoEhpctU/edit#slide=id.gc6f73a04f_0_0

Example: https://github.com/carlosvillu/UABTexthandler

**Comment by sergioalvz** [comment]
April 30th: Chapter 14 (Shahved)

**Comment by sergioalvz** [comment]
May 7th: chapter 15 (David)

**Comment by sergioalvz** [comment]
May 21st: 16 (@SantiMA10)

**Comment by sergioalvz** [comment]
May 28th: 17 (Rober)

**Comment by SantiMA10** [comment]
Jun 4th: 18 (-)

**Comment by SantiMA10** [comment]
Jun 4th: 19 (Shahved)

**Comment by SantiMA10** [comment]
Jun 18th: chapter 20 (David)

**Comment by SantiMA10** [comment]
Jun 25th: chapter 20 & 21 (David)

**Comment by SantiMA10** [comment]
Jul 2nd: chapter 22 (Santi)

**Comment by SantiMA10** [comment]
Jul 9nd: chapter 23 (Rober)

**Comment by SantiMA10** [comment]
Jul 23rd: chapter 24 (Imanol)

**Comment by SantiMA10** [comment]
Jul 30th: chapter 25 (David)

**Comment by SantiMA10** [comment]
Aug 6th: 26 & 27 (Shahved)

**Comment by SantiMA10** [comment]
Aug 13th: 28 & 29 (Santi)

**Comment by SantiMA10** [comment]
Aug 20th: 30 & 31 (Rober)

**Comment by SantiMA10** [comment]
Aug 28rd: chapter 32 & 33 (Imanol)

**Comment by SantiMA10** [comment]
Sep 3rd: chapter 34 (David)
