### ISSUE TITLE
Designing Data-Intensive Applications

### ISSUE THREAD

**Issue by sergioalvz** [privacycloud/book-club#23]
# Designing Data-Intensive Applications: The Big Ideas Behind Reliable, Scalable, and Maintainable Systems

> Data is at the center of many challenges in system design today. Difficult issues need to be figured out, such as scalability, consistency, reliability, efficiency, and maintainability. In addition, we have an overwhelming variety of tools, including relational databases, NoSQL datastores, stream or batch processors, and message brokers. What are the right choices for your application? How do you make sense of all these buzzwords?
> 
> In this practical and comprehensive guide, author Martin Kleppmann helps you navigate this diverse landscape by examining the pros and cons of various technologies for processing and storing data. Software keeps changing, but the fundamental principles remain the same. With this book, software engineers and architects will learn how to apply those ideas in practice, and how to make full use of data in modern applications.

- What is it?
  - [x] A book 📚
  - [ ] An article 📄
  - [ ] Other
- Link: https://dataintensive.net/

**Comment by SantiMA10** [comment]
Sep 24th: Chapter 3 (Rober)

**Comment by shahved** [comment]
Oct 1st: Chapter 4 (Shahved)

**Comment by SantiMA10** [comment]
Oct 8th: Chapter 5 (Leaders and Followers & Problems with Replication Lag) (David)

**Comment by SantiMA10** [comment]
Oct 15th: Chapter 5 (Part II) (Santi)

**Comment by SantiMA10** [comment]
Oct 22th: Chapter 6 (Rober)

**Comment by miguelff** [comment]
Excellent resource, folks! I'm reading it too!

**Comment by shahved** [comment]
We meet Tuesdays at 16:00 hrs (GMT+2), if you'd like to join us :)

**Comment by SantiMA10** [comment]
Oct 29th: Chapter 7 (I & II) (Shahved)

**Comment by SantiMA10** [comment]
Nov 5th: Chapter 7 (Santi)

**Comment by SantiMA10** [comment]
Nov 26th: Chapter 8 (David) (I, II y III)

**Comment by SantiMA10** [comment]
@shahved @daviceitor RobertoM should we close this issue?
